version: '3.8'

services:
    # Servicio de la aplicación Laravel
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        volumes:
            - .:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        ports:
            - "9000:9000"
        networks:
            - app-network
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - APP_KEY=${APP_KEY}
        depends_on:
            - mysql

    # Servicio de base de datos MySQL
    mysql:
        image: mysql:8.0
        container_name: mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: laravel_db
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: laravel_password
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - app-network
        ports:
            - "3306:3306"

    # Servicio de Nginx para servir Laravel
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - app
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    dbdata:
        driver: local
